# Generated by Django 5.1.6 on 2025-03-15 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0003_alter_interview_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='json_response',
            field=models.CharField(blank=True, max_length=30000, null=True),
        ),
    ]
