# Generated by Django 5.1.6 on 2025-03-19 04:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0004_interview_json_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='feedback',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='interview',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='interview.interview'),
        ),
        migrations.AlterField(
            model_name='question',
            name='user_answer',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
