# Generated by Django 5.1.6 on 2025-03-26 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0006_alter_interview_json_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='json_response',
            field=models.TextField(blank=True, max_length=16000, null=True),
        ),
    ]
